### ISSUE TITLE
First line of data in loop is not received properly

### ISSUE THREAD

**Issue by jarredglickstein** [ppetr/arduino-influxdb#3]
I've configured an Arduino nano to read sensor data once every 5 minutes and write through the serial port at 9600 baud. The arduino-influxdb collect.py script always misses the first line of data in the loop, but receives all remaining lines successfully. So as a workaround I configured my Arduino code to write a dummy line before sending relevant data points. Sample data from the Arduino as observed on the Arduino serial monitor appears as: 

livingroom,sensor=dummy dummydata=1024
livingroom,sensor=sensor1 temperature=24.68
livingroom,sensor=sensor1 pressure=97.83
livingroom,sensor=sensor1 humidity=50.27,altitude=295.22
livingroom,sensor=sensor1 gas_resistance=361128.00
livingroom,sensor=sensor2 temperature=25.20,humidity=55.20

I then close the Arduino software and run the arduino-influxdb script using the command: 

python collect.py --debug -d /dev/ttyUSB0 -H localhost:8086 -D livingroom

Then once every 5 minutes I get the following sample output: 

DEBUG:root:Received line ''
ERROR:root:Error, retrying with backoff
Traceback (most recent call last):
  File "collect.py", line 42, in ReadLoop
    args.max_line_length):
  File "/home/user/arduino-influxdb/serial_samples.py", line 99, in SerialLines
    raise LineOverflowError(line)
LineOverflowError: Received incomplete line ''
DEBUG:root:Read loop started
DEBUG:root:Skipping until the end of a new line.
DEBUG:root:Received line 'livingroom,sensor=sensor1 temperature=24.68\r\n'
DEBUG:root:Sending lines: ['livingroom,sensor=sensor1 temperature=24.68 1597596641434375168']
DEBUG:root:Received line 'livingroom,sensor=sensor1 pressure=97.83\r\n'
DEBUG:root:Sending lines: ['livingroom,sensor=sensor1 pressure=97.83 1597596641631673088']
DEBUG:root:Received line 'livingroom,sensor=sensor1 humidity=50.27,altitude=295.22\r\n'
DEBUG:root:Sending lines: ['livingroom,sensor=sensor1 humidity=50.27,altitude=295.22 1597596642180745984']
DEBUG:root:Received line 'livingroom,sensor=sensor1 gas_resistance=361128.00\r\n'
DEBUG:root:Sending lines: ['livingroom,sensor=sensor1 gas_resistance=361128.00 1597596642417794048']
DEBUG:root:Received line 'livingroom,sensor=sensor2 temperature=25.20,humidity=56.20\r\n'
DEBUG:root:Sending lines: ['livingroom,sensor=sensor2 temperature=25.20,humidity=56.20 1597596642626853888']

I have tried including a 250-1000 ms delay between lines to see if this changes anything, no change. Also tried replacing "\r\n" with "\n" since I'm on Linux, still does not work. Note also I was  previously writing multiple data values at a time, i.e.

"livingroom,sensor=sensor1 temperature=24.68,pressure=97.83,humidity=50.27,altitude=295.22"

I thought perhaps the lines were too long or that the Arduino Serial.print was taking too long to write a line, so I split each data point onto its own line. This also does not resolve the issue.

**Comment by ppetr** [comment]
Hi Jarred,

This is actually on purpose. The reason is that when the script starts and
starts reading from the serial port, it can't reliably detect if it doesn't
start reading from the middle of a line. So it skips the first line to make
sure it doesn't read and send malformed data. You can see in the logs
line *"Skipping
until the end of a new line"*. Perhaps I should document the behavior.

All the best,
Petr

>

**Comment by jarredglickstein** [comment]
Aha, I had incorrectly concluded that log line indicated an error. So I see this once at the start of every write loop, given this is the intended behavior that explains why writing one dummy line at the start of each 5 minute loop works. 

Some documentation would be helpful. I will guess the argument --read-timeout is the amount of time after receiving a dummy line during which the program will parse complete lines received by the serial port and that the default 60 is in units of seconds? Meaning there is a 60 second window after writing a dummy line in which new data will be properly received, after which time I need to write a dummy line before sending new information again.

**Comment by jarredglickstein** [comment]
By the way, you have made an excellent tool here, thank you for sharing it! I have 3 sensors each within 20 feet of a server and it doesn't make any sense to connect them over the internet. USB it is. Here's a little sample. Once I got the delay loop timing on the Arduinos correct to account for the Arduino's poor ability to keep time (as if these microcontrollers ask, "what's a millisecond, 3π?"), the results are truly spectacular. 

![sample_sensor_data](https://user-images.githubusercontent.com/3357434/91191358-adac1000-e6c2-11ea-9989-16e8106aea44.png)

**Comment by ppetr** [comment]
> By the way, you have made an excellent tool here, thank you for sharing it!

I'm very happy to hear that! I'm glad that it's useful to you!

> Some documentation would be helpful. I will guess the argument --read-timeout is the amount of time after receiving a dummy line during which the program will parse complete lines received by the serial port and that the default 60 is in units of seconds?

Argument `--read-timeout` is passed to [_pyserial_](https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial). From its documentation:

> ... (`read`) returns immediately when the requested number of bytes are available, otherwise wait until the timeout expires and return all bytes that were received until then.

This means that when the program tries to read a full line in its main loop, it waits until either `\n` is received or this time elapses.
I wrote the code to always prefer losing data over misinterpreting it. If it happens that a timeout happens and a line is read without an ending `\n`, it means it wasn't read completely, and the main loop fails with an exception. This restarts it from the beginning, and it again starts with reading until a `\n` is received. During this initial phase, the read timeout has no effect. The program simply waits until `\n` is received, regardless of timeouts.

This means that `--read-timeout` should be longer than the period of how frequently Arduino sends its data. Indeed, I will better document that. If it's shorter, you'll get such exceptions in the main loop and then miss the next line.

I'm considering making also another improvement: If the program times out on an empty line, it means nothing was received, and then there is no need for throwing this exception. But this would mean a dead Arduino would never be detected, the program would be waiting forever like nothing is happening.

**Comment by ppetr** [comment]
As a simple solution, I'll make `--read_timeout` mandatory (and extend its documentation) to make its value explicit.
