### ISSUE TITLE
How to improve stability? (InfluxdbError: Request failed)

### ISSUE THREAD

**Issue by papatistos** [ppetr/arduino-influxdb#4]
Thanks for this script! It is working quite okay for me but not reliably enough to forget about it. Every couple of days, the influxDB stops accepting the data, issuing a 400 error with reason "Bad request":

~~~~
DEBUG:root:Write loop started
DEBUG:root:Sending lines: ['FTX_log ventstate=1,ledventstate=1,brightness=43i,desiredventstate=1,error0=34i,error1=0i,error2=0i,lederror=0i,timerup=516422727i,timerdown=0i,timerhigh=0i,old_t_vals0=0i,old_t_vals1=0i,old_t_vals2=0i,old_h_v,old_h_vals1=0i,old_h_vals2=0i,sensorerrors0=200i,sensorerrors1=212i,sensorerrors2=208i,h-index=6,end=2 1599871804525667072']
ERROR:root:Error, retrying with backoff
Traceback (most recent call last):
  File "collect.py", line 57, in WriteLoop
    influxdb.PostSamples(args.database, args.host, [influxdb_line])
  File "/home/christoph/arduino-influxdb-master/influxdb.py", line 46, in PostSamples
    raise InfluxdbError(params, body, response)
InfluxdbError: Request failed (status='400', reason='Bad Request', params='db=FTX2&precision=ns'): FTX_log ventstate=1,ledventstate=1,brightness=43i,desiredventstate=1,error0=34i,error1=0i,error2=0i,lederror=0i,timerup=516422727i,timerdown=0i,timerhigh=0i,old_t_vals0=0i,old_t_vals1=0i,old_t_vals2=0i,old_h_v,old_h_vals1=0i,old_h_vals2=0i,sensorerrors0=200i,sensorerrors1=212i,sensorerrors2=208i,h-index=6,end=2 1599871804525667072
~~~~
I cannot see what the problem with this request is.

The command I used was this: 
~~~~
python collect.py -d /dev/ttyUSB0 -H 192.168.1.4:8086 -D FTX2 -q queue --debug > collect.log 2>&1
~~~~

Here is a request from earlier in the same log which worked fine:
~~~~
DEBUG:root:Received line 'FTX_log ventstate=1,ledventstate=1,brightness=41i,desiredventstate=1,error0=0i,error1=0i,error2=0i,lederror=0i,timerup=180078i,timerdown=0i,timerhigh=180078i,old_t_vals0=0i,old_t_vals1=0i,old_t_vals2=0i,old_h_vals0=0i,old_h_vals1=0i,old_h_vals2=0i,sensorerrors0=0i,sensorerrors1=0i,sensorerrors2=0i,h-index=0,end=2\r\n'
DEBUG:root:Sending lines: ['FTX_log ventstate=1,ledventstate=1,brightness=41i,desiredventstate=1,error0=0i,error1=0i,error2=0i,lederror=0i,timerup=180078i,timerdown=0i,timerhigh=180078i,old_t_vals0=0i,old_t_vals1=0i,old_t_vals2=0i,old_h_vals0=0i,old_h_vals1=0i,old_h_vals2=0i,sensorerrors0=0i,sensorerrors1=0i,sensorerrors2=0i,h-index=0,end=2 1599353791303456000']
~~~~

Why does it suddenly stopp accepting exactly the same kind of values?

Whatever the reason is, wouldn't it make sense for the collect.py script to eventually stop sending that line and try with the next one in the queue? Because, from what I can tell, what happens once a request to influxDB fails is that the script keeps trying to send the same line over and over again and I see no way of telling it: drop it and try the next one in teh queue. Also, I haven't been able to figure out how I can use my queue database to send whatever is in there to influxDB. Could you clarify this?

**Comment by ppetr** [comment]
Thanks for the report! You're right, the script tries to send all values it ever receives. If there is an error, it retries indefinitely. Everything is stored in a SQLite database, which is by default in memory. So when you restart the script, the database is lost, and the script functions until another invalid line is received. If you used an on-disk database, it'd retry the invalid line forever.

I followed this approach, because from my experience such errors were always a problem on my side, a wrong line sent by my Arduino. And I wanted to detect and fix such errors.

I could add a flag to skip over invalid lines. But this would need to be done very carefully. If there is a problem with the database, or with a connection to it, such failures should be retried. Looking at the [documentation](https://docs.influxdata.com/influxdb/v1.8/tools/api/#status-codes-and-responses-1), skipping only over  error codes 400 (`Bad Request`) could be safe enough. I'll also check if it's possible to print the returned JSON response, which might contain useful debug information.

**Comment by papatistos** [comment]
Thanks for your excellent reply. So I take it that you can't see either what the difference between the two sent lines is, where one gets a 204 and the other a 400. In that case it would indeed be very useful if you could print the JSON response.

As for wanting it to fail in order to track down bugs, I understand where you're coming from but it's also a pity that that "feature" renders the queue worthless in case of failure (right?). I renamed my queue database files just in case there is a way to recover the data... 

So a flag for skipping over invalid lines would be useful. If it is too complicated to have the script do it automatically *and* reliably, it might also help if it could be done manually. For example, the script could check for a file called `skip_error` and if it's present, it will skip not retry upon error (or only retry a few times). Once it's worked itself through the accumulated queue, the file could be removed. 

An even more manual solution would be to check for a file named `skip_timecode`, which would contain a timecode range  and the script would ignore any data within that timespan. That way I could start by skipping the timecode of the failing line and if the next one also fails, extend the range and so on.

While I'm at it, I might as well mention that I'm having troubles stopping the script. It seems I have to use `kill`. But I'm not very versed in Linux commands, especially when it comes to process handling, so If that's by design (stability?), what is the correct way to stop the script?

**Comment by ppetr** [comment]
Please try the new option introduced in branch _4-request-failed_ (63e00be79d9018c9cb3fa2f9c7b5c19dbbe97b39).

At the moment I have no environment where to test it, so it might be buggy, or even fail to compile properly.

**Comment by papatistos** [comment]
Wow, that was fast! Thanks for the fix!

I just switched to the new branch and it seems to work. I'll let it run and I'll let you know when/if it ever fails again. 
For the record, I did `python collect.py -d /dev/ttyUSB0 -H 192.168.1.4:8086 -t 80 -D FTX2 -q queue --warn_on_status 400 --debug > collect.log 2>&1`. Looking at the code, I realize that the `400` was not necessary because it's the default.

I just realize that this new option can make handling of `nan` values significantly easier. I don't need it because I coded my sektch [so that it will never send a `nan` value](https://github.com/tophee/FTXcontrol-Shield/blob/56e8436d04292b71e5585b76d5dc8d8f4f8ca64b/FTXcontrol-shield.ino#L262-L285), but for many use cases it would be completely fine if you just let the Arduino send those `nan` values and let influxDB reject them (although it would probably be cleaner to let the script check for `nan` values and remove just that measurement instead of the entire line).

**Comment by ppetr** [comment]
Good to hear! Can you please confirm that you see the JSON response from Influx DB in the logs now?

> I just realize that this new option can make handling of nan values significantly easier. ...

It's true that I could check the validity of received lines in the script, but that'd mean coupling it tightly with InfluxDB's format and making sure it follows any future changes. So I'd better keep it as it is, letting InfluxDB reject any such lines with error 400.
