### ISSUE TITLE
How to use telegraf? 

### ISSUE THREAD

**Issue by papatistos** [ppetr/arduino-influxdb#5]
I'm trying to use the script with telegraf (which is new to me) and I'm not succeeding. Telegraf is sending its monitoring data about CPU usage but I can't get it to send the Arduino data coming from the script. So I'm wondering whether I went down a wrong path when I tried to use the InfluxDB Listener Input Plugin for this. I set it up to listen at port 8089, I think, and then instructed the script to send to localhost:8089 instead of the IP and port of InfluxDB. Is this how its meant to be done?

**Comment by ppetr** [comment]
Could you share the relevant part of Telegraf's config? Mine looks like this:

```
# Influx HTTP write listener
[[inputs.http_listener]]
  ## Address and port to host HTTP listener on
  service_address = ":8186"

  ## maximum duration before timing out read of the request
  read_timeout = "10s"
  ## maximum duration before timing out write of the response
  write_timeout = "10s"

  ## Maximum allowed http request body size in bytes.
  ## 0 means to use the default of 536,870,912 bytes (500 mebibytes)
  # max_body_size = 0
  max_body_size = 1024000

  ## Maximum line size allowed to be sent in bytes.
  ## 0 means to use the default of 65536 bytes (64 kibibytes)
  max_line_size = 0
```

My script connects to localhost:8186 and this sends data to the database configured in `[[outputs.influxdb]]`.

**Comment by papatistos** [comment]
My config looks basically the same. (Note that the `inputs.http_listener` that you are using has been renamed to `inputs.influxdb_listener` (https://github.com/influxdata/telegraf/blob/release-1.15/plugins/inputs/influxdb_listener/README.md)

Here is my config:

~~~~
[[inputs.influxdb_listener]]
#   ## Address and port to host InfluxDB listener on
   service_address = ":8186"
#
#   ## maximum duration before timing out read of the request
   read_timeout = "10s"
#   ## maximum duration before timing out write of the response
   write_timeout = "10s"
#
#   ## Maximum allowed HTTP request body size in bytes.
#   ## 0 means to use the default of 32MiB.
   max_body_size = "32MiB"
#
#   ## Optional tag name used to store the database.
#   ## If the write has a database in the query string then it will be kept in this tag name.
#   ## This tag can be used in downstream outputs.
#   ## The default value of nothing means it will be off and the database will not be recorded.
#   # database_tag = ""
#
#   ## If set the retention policy specified in the write query will be added as
#   ## the value of this tag name.
#   # retention_policy_tag = ""
#
#   ## Set one or more allowed client CA certificate file names to
#   ## enable mutually authenticated TLS connections
#   tls_allowed_cacerts = ["/etc/telegraf/clientca.pem"]
#
#   ## Add service certificate and key
#   tls_cert = "/etc/telegraf/cert.pem"
#   tls_key = "/etc/telegraf/key.pem"
#
#   ## Optional username and password to accept for HTTP basic authentication.
#   ## You probably want to make sure you have TLS configured above for this.
#   # basic_username = "foobar"
#   # basic_password = "barfoo"
~~~~

And yes, my script also connects to `localhost:8186`.  Let me just double check, to be sure...

Scrolling up in my terminal window I find: `python collect.py -d /dev/ttyUSB0 -H localhost:8186 -D FTX2 -q queue2 --debug > collect2.log 2>&1`. I also tried `python collect.py -d /dev/ttyUSB0 -H 127.0.0.1:8186 -D FTX2 -q queue3 --debug > collect3.log 2>&1` 

Now, when it comes to "to the database configured in `[[outputs.influxdb]]`", that is not the same as in the command above. Does it have to be? I was going to keep the server metrics separate from the Arduino sensor data. But maybe that's not how you're supposed to do it?

Well, it looks like it. I just found a couple of arduino sensor values in the other database. So the reason I didn't see anything in `FTX2` was that telegraf ignored the database and just used the one from `[[outputs.influxdb]]`. What a bummer. But at least that  explains things.

**Comment by ppetr** [comment]
> Well, it looks like it. I just found a couple of arduino sensor values in the other database

I'm afraid that's how it works. I have the same experience. It ignores the target database, and writes always to the one in its config file. It's a bit unfortunate.

For this, I have only two solutions: Use Telegraf only with a single database. Or simply connect to the target database directly. Now _arduino-influxdb_ uses a persistent queue internally, so no data points are lost, even if there is no connectivity for a long time. (And Telegraf buffers only limited amount of data.)

I think there isn't much else to do, so I'm closing this issue. If you encounter any further problems, please reopen.
