### ISSUE TITLE
Allow resume queue

### ISSUE THREAD

**Issue by papatistos** [ppetr/arduino-influxdb#6]
Feature suggestion:

Before creating the queue database (and possibly overwriting an existing one by the same name), check if it already exists and if it does, use it. That way, data in the queue doesn't get lost and is sent to influxDB when the script is executed the next time.

**Comment by ppetr** [comment]
The script should never overwrite an existing database. But by default, the database is set to [_:memory:_](https://www.sqlite.org/inmemorydb.html), which means the database exists only in RAM and is lost every time the script restarts.

**Comment by papatistos** [comment]
>The script should never overwrite an existing database.

Oh! that's great! So that means the suggested feature already exists? I wrote all my queues on disk (but used different filenames so as to not overwrite previous data. Will try to re-use those filenames and check influxdb if the gaps in the data will be filled in...

**Comment by ppetr** [comment]
I hope it worked well for you. Yes, the queue is persistent like that. You only need to specify the file name, and the script handles everything on its own. The queue adheres to the standard [ACID](https://sqlite.org/transactional.html) properties, as it's internally based on SQLite.

**Comment by papatistos** [comment]
Could it be that the `--warn_on_status` option only works for data arriving directly from the serial port but not for data waiting in the queue? 

I just fiddled with my sensors (which led to som nan values) and my network (so that the influxdb server may not have been available all the time). So when everything was up and running again, I also started the collect script. I'm not sure exactly what went wrong, but here is what I just got:

~~~~
$ python /home/christoph/arduino-influxdb-4-request-failed/collect.py -d /dev/ttyUSB0 -H 192.168.1.4:8086 -t 80 -D FTX2 -q queue  --warn_on_status --debug
DEBUG:root:Read loop started
DEBUG:root:Write loop started
DEBUG:root:Sending lines: ['FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152']
ERROR:root:Error, retrying with backoff
Traceback (most recent call last):
  File "/home/christoph/arduino-influxdb-4-request-failed/collect.py", line 59, in WriteLoop
    [influxdb_line])
  File "/home/christoph/arduino-influxdb-4-request-failed/influxdb.py", line 55, in PostSamples
    raise error
InfluxdbError: Request failed (status='400', reason='Bad Request', response='{"error":"unable to parse 'FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152': invalid number"}
', params='db=FTX2&precision=ns'): FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152

DEBUG:root:Skipping until the end of a new line.
DEBUG:root:Write loop started
DEBUG:root:Sending lines: ['FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152']
ERROR:root:Error, retrying with backoff
Traceback (most recent call last):
  File "/home/christoph/arduino-influxdb-4-request-failed/collect.py", line 59, in WriteLoop
    [influxdb_line])
  File "/home/christoph/arduino-influxdb-4-request-failed/influxdb.py", line 55, in PostSamples
    raise error
InfluxdbError: Request failed (status='400', reason='Bad Request', response='{"error":"unable to parse 'FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152': invalid number"}
', params='db=FTX2&precision=ns'): FTX,status=testing elapsed=602882i,t0=0.00,t1=0.00,t2=0.00,rh0=0.00,ah0=0.0,rh1=0.00,ah1=0.0,rh2=0.00,ah2=0.0,dew0=nan,dew1=nan,dew2=nan,h-eff=nan,t-eff=nan,hum-gain=0.00,CR0-1=0.00,CR0-2=0.00,CR2-1=0.00,CR2-2=0.00,end=1 1601757507811217152
~~~~

The timestamp is from 8:38 pm, which was when I started fiddling more than three hours ago. So it is reading this from the queue file, which is fine, but it seems to be retrying instead of dropping the line as instructed by `--warn_on_status`.

**Comment by papatistos** [comment]
Quick update: I just saw the same issue again so I tried using `--warn_on_status 400` instead of  `--warn_on_status` and then it worked. So either the implied `400` doesn't work with the database queue or perhaps not at all. I guess that's not a problem. Maybe it was just me assuming that 400 was the default value? I thought I read that somewhere, but I can't find it now. Nevermind.
